config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'static_pages#home'
  get '/terms' => 'static_pages#terms', as: 'terms'
  get '/privecy' => 'static_pages#privecy', as: 'privecy'

  resource :user do
    resource :profile, except: [:destroy]
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_profile, only: [:edit, :update, :show]

  def new
    @profile = current_user.build_profile
  end

  def create
    current_user.build_profile(permitted_params).save
    redirect_to edit_user_profile_path
  end

  def edit; end

  def update
    @profile.update_attributes(permitted_params)
    redirect_to edit_user_profile_path
  end

  def show; end

  protected

  def find_profile
    @profile = current_user.profile
  end

  def permitted_params
    params.require(:profile).permit(:first_name, :last_name, :dob, :address, :phone_number)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_profile_form.html.erb
<div class="panel panel-default col-md-6 col-md-offset-3">
  <div class="panel-heading">
    <h1>Profile Detail</h1>
  </div>
  <div class="panel-body">

    <%= simple_form_for @profile, url: user_profile_path do |f| %>
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :dob, as: :string, label: 'Date of Birth', input_html: { class: 'date_select' } %>
      <%= f.input :address %>
      <%= f.input :phone_number %>

      <%= f.button :submit, class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/edit.html.erb
<%= render partial: 'profile_form' %>

app/views/profiles/new.html.erb
<%= render partial: 'profile_form' %>

app/views/profiles/show.html.erb
<h1>Profiles#show</h1>
<p>Find me in app/views/profiles/show.html.erb</p>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>