config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root 'static_pages#home'
  get '/terms' => 'static_pages#terms', as: 'terms'
  get '/privecy' => 'static_pages#privecy', as: 'privecy'

  resource :user do
    resource :profile, except: [:destroy]
  end

end

app/views/layouts/_footer.html.erb
<ul>
  <li>
    <%= link_to 'Terms', terms_path %>
  </li>
  <li>
    <%= link_to 'Privacy', privecy_path %>
  </li>
</ul>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li class="dropdown-toggle show-on-hover" data-toggle="dropdown"><%= image_tag current_user.image.present? ? current_user.image : "#{SITE_BASE_URL}assets/user.png"%>
      <ul class="dropdown-menu" style="z-index: 9999;">
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to 'Edit Profile', current_user.profile.present? ? edit_user_profile_path : new_user_profile_path, method: :get  %></li>
        <li><%= link_to 'User Settings', 'javascript:;' %></li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<html>
  <head>
    <%= stylesheet_link_tag 'application', {:media => :all} %>
    <%=javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
</html>
<div class="container-narrow col-md-12">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h3 class="muted"><%= link_to "SimpleDevise", root_path %></h3>
    <h5 class="muted">A demo of using SimpleDB with Devise</h5>
  </div>
  <hr />
  <%= yield %>
  <div style="clear: both"></div>
  <footer class="page__footer">
    <% if content_for? :footer %>
      <%= yield :footer %>
    <% else %>
      <%= render 'layouts/footer' %>
    <% end %>
  </footer>
</div>